name: appdulich
description: "Dự án App Du Lịch - Nhóm 10"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- Cấu hình Firebase ---
  firebase_core: ^3.6.0         # Thư viện lõi kết nối Firebase
  firebase_auth: ^5.3.1         # Chức năng Đăng nhập / Đăng ký
  cloud_firestore: ^5.4.4       # Cơ sở dữ liệu lưu Tour, Địa điểm, Bài viết

  # --- Thư viện bổ trợ nên có cho App Du Lịch ---
  google_fonts: ^6.2.1          # Sử dụng font chữ hiện đại (Roboto, Montserrat...)
  cached_network_image: ^3.4.1  # Load ảnh từ internet nhanh, mượt, không bị giật
  provider: ^6.1.2              # Quản lý trạng thái ứng dụng (State Management)
  image_picker: ^1.2.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Cấu hình Assets sau này (nếu bạn muốn dùng ảnh có sẵn trong máy)
  # assets:
  #   - assets/images/