// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPj7Krzrzk6OwbbDcKJs_qYUKzMyR9iQg',
    appId: '1:716371529404:web:ab9dcdef6efb6fbfb78ab9',
    messagingSenderId: '716371529404',
    projectId: 'appdulich-e7c38',
    authDomain: 'appdulich-e7c38.firebaseapp.com',
    storageBucket: 'appdulich-e7c38.firebasestorage.app',
    measurementId: 'G-WNPXH5NGXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKwVBHt24gXm_PnV1UlQSanLNEmwMx2Zk',
    appId: '1:716371529404:android:a241a69cc317a108b78ab9',
    messagingSenderId: '716371529404',
    projectId: 'appdulich-e7c38',
    storageBucket: 'appdulich-e7c38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb04K0dvuii6bq0KhVqXKvgTErURpK-X8',
    appId: '1:716371529404:ios:9e6e143c1b2c8131b78ab9',
    messagingSenderId: '716371529404',
    projectId: 'appdulich-e7c38',
    storageBucket: 'appdulich-e7c38.firebasestorage.app',
    iosBundleId: 'com.example.appdulich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb04K0dvuii6bq0KhVqXKvgTErURpK-X8',
    appId: '1:716371529404:ios:9e6e143c1b2c8131b78ab9',
    messagingSenderId: '716371529404',
    projectId: 'appdulich-e7c38',
    storageBucket: 'appdulich-e7c38.firebasestorage.app',
    iosBundleId: 'com.example.appdulich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPj7Krzrzk6OwbbDcKJs_qYUKzMyR9iQg',
    appId: '1:716371529404:web:edd3493574dac5f9b78ab9',
    messagingSenderId: '716371529404',
    projectId: 'appdulich-e7c38',
    authDomain: 'appdulich-e7c38.firebaseapp.com',
    storageBucket: 'appdulich-e7c38.firebasestorage.app',
    measurementId: 'G-121F4LQN7C',
  );
}
